### ISSUE TITLE
샘플 이미지 drag & drop 구현

### ISSUE THREAD

**Issue by SaraHan774** [Dolhareubang/hareubang-client#21]
사진 위에다가 아무 이미지나 올려두는 것 구현할 예정.

**Comment by DonghyunKim98** [comment]
미리 어느 위치에 올려놓는지 받아오는 API 구축까지 진행하는건 어떤가요

**Comment by SaraHan774** [comment]
아마 내가 사용하려는 라이브러리에 위치에 대한 값도 읽어올 수 있는 기능이 포함된 것 같아서, 우선은 그 라이브러리가 적합한지 먼저 볼게 !
